name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - {OS_NAME: ubuntu, OS_CODE_NAME: focal, ROS_DISTRO: noetic, DOCKER_IMAGE: "samxl/scancontrol:sdk_v1.0.0"}
    env:
      CCACHE_DIR: /github/home/.ccache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ccache-${{ matrix.env.ROS_DISTRO }}-${{ matrix.env.ROS_REPO }}
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{ matrix.env }}
  
  clang_format_check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - {OS_NAME: ubuntu, OS_CODE_NAME: focal, ROS_DISTRO: noetic, DOCKER_IMAGE: "samxl/scancontrol:sdk_v1.0.0"}
  
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run industrial_ci with Clang Format check
      uses: ros-industrial/industrial_ci@master
      env: ${{ matrix.env }}
      with:
        BUILD_TOOL: catkin
        CATKIN_LINT: 'false'
        CLANG_FORMAT_CHECK: "file"
        CLANG_FORMAT_VERSION: "10"

        # You might need to adjust the path if your package is not at the root of the repository
        CATKIN_PKGS: "$(basename $GITHUB_REPOSITORY)"
  